module.exports.testSeed = [{
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": 14,
  "Class_id": 7
}, {
  "testName": "Training",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 5
}, {
  "testName": "Engineering",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 10
}, {
  "testName": "Engineering",
  "type": "Lecture",
  "timeAllowed": 0,
  "Class_id": 6
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 13
}, {
  "testName": "Support",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 10
}, {
  "testName": "Support",
  "type": "Lecture",
  "timeAllowed": 5,
  "Class_id": 9
}, {
  "testName": "Accounting",
  "type": "Lecture",
  "timeAllowed": 8,
  "Class_id": 6
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 12
}, {
  "testName": "Business Development",
  "type": "Lecture",
  "timeAllowed": 16,
  "Class_id": 12
}, {
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 11
}, {
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 7
}, {
  "testName": "Legal",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 9
}, {
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 6
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 9
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 5
}, {
  "testName": "Product Management",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 6
}, {
  "testName": "Legal",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 10
}, {
  "testName": "Engineering",
  "type": "Lecture",
  "timeAllowed": 1,
  "Class_id": 12
}, {
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 14
}, {
  "testName": "Support",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 11
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 11
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 13
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": 20,
  "Class_id": 11
}, {
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 11
}, {
  "testName": "Sales",
  "type": "Lecture",
  "timeAllowed": 13,
  "Class_id": 15
}, {
  "testName": "Marketing",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 11
}, {
  "testName": "Sales",
  "type": "Lecture",
  "timeAllowed": 29,
  "Class_id": 6
}, {
  "testName": "Engineering",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 9
}, {
  "testName": "Marketing",
  "type": "Lecture",
  "timeAllowed": 17,
  "Class_id": 12
}, {
  "testName": "Training",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 11
}, {
  "testName": "Research and Development",
  "type": "Lecture",
  "timeAllowed": 10,
  "Class_id": 8
}, {
  "testName": "Support",
  "type": "Lecture",
  "timeAllowed": 6,
  "Class_id": 12
}, {
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 7
}, {
  "testName": "Services",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 15
}, {
  "testName": "Marketing",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 13
}, {
  "testName": "Support",
  "type": "Lecture",
  "timeAllowed": 26,
  "Class_id": 12
}, {
  "testName": "Product Management",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 12
}, {
  "testName": "Business Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 9
}, {
  "testName": "Business Development",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 5
}, {
  "testName": "Training",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 8
}, {
  "testName": "Product Management",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 10
}, {
  "testName": "Sales",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 13
}, {
  "testName": "Human Resources",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 8
}, {
  "testName": "Engineering",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 13
}, {
  "testName": "Marketing",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 13
}, {
  "testName": "Engineering",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 13
}, {
  "testName": "Support",
  "type": "Lecture",
  "timeAllowed": 26,
  "Class_id": 12
}, {
  "testName": "Human Resources",
  "type": "Lecture",
  "timeAllowed": null,
  "Class_id": 12
}, {
  "testName": "Marketing",
  "type": "Lecture",
  "timeAllowed": 25,
  "Class_id": 14
}];